#!/usr/bin/env python3
"""Shared configuration for the eye-to-hand SORACAM vision pipeline.

One fixed source of truth for: the ChArUco board geometry (so the printed board,
the calibrators and `locate` all agree), the on-disk calibration artifacts, the
frame source, and the GRASP-HEIGHT CONSTRAINT (we do NOT observe object height
from a single view — it is a configured constant per object class, by design).

Everything here is plain data; importing this module never touches the robot,
the camera, or OpenCV.
"""

from __future__ import annotations

import os
from dataclasses import dataclass, field
from typing import List

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))            # project root
ARTIFACT_DIR = os.path.join(HERE, "calib")              # calibration outputs live here


def _load_dotenv(path: str) -> None:
    """Load simple KEY=VALUE lines into os.environ (without overriding existing).

    Lets the brain hold SORACOM creds in a gitignored scripts/vision/.soracom.env
    so the one-shot grab tools work without the MCP. Never logged.
    """
    if not os.path.isfile(path):
        return
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            os.environ.setdefault(k.strip(), v.strip().strip('"').strip("'"))


_load_dotenv(os.path.join(HERE, ".soracom.env"))

# --- artifact file names (under ARTIFACT_DIR) -------------------------------
HOMOGRAPHY_JSON = "homography.json"      # pixel<->board-plane homography (step A)
HANDEYE_JSON = "board_to_base.json"      # board->base (similarity) transform (step B)


# --- ChArUco board (A4) -----------------------------------------------------
# PHYSICAL BOARD (2026-06-08 reprint, verified on the eye-to-hand SORACAM frame):
# 10 x 7 ChArUco, DICT_4X4_50, big markers (ratio 0.79). Generated by
# board_to_pdf.py and printed A4. The original DICT_6X6_250 board decoded only
# ~16/35 markers (markers too small -> ~40% board coverage); the 4x4 reprint
# decodes 33/35 and yields 50/54 corners across the FULL board.
#
# IMPORTANT: square_length_mm MUST be the TRUE printed size (it sets the metric
# scale of every pick coordinate). MEASURE one square with a ruler/calipers and
# set it here. marker_length_mm only affects detection robustness (the pose
# comes from the chessboard corners).
@dataclass(frozen=True)
class BoardSpec:
    squares_x: int = 10                      # columns
    squares_y: int = 7                       # rows
    square_length_mm: float = 28.0           # TODO: set to the MEASURED square edge
    marker_length_mm: float = 22.0           # 0.79 * square (detection-friendly reprint)
    dictionary: str = "DICT_4X4_50"          # cv2.aruco predefined dict name
    # The board frame: origin at the board corner, +X along squares_x, +Y along
    # squares_y, +Z out of the board toward the camera. OpenCV's CharucoBoard
    # uses exactly this convention, with chessboard corners at integer multiples
    # of square_length in the XY plane (Z=0).

    @property
    def width_mm(self) -> float:
        return self.squares_x * self.square_length_mm

    @property
    def height_mm(self) -> float:
        return self.squares_y * self.square_length_mm

    @property
    def n_corners(self) -> int:
        # interior chessboard corners
        return (self.squares_x - 1) * (self.squares_y - 1)


BOARD = BoardSpec()


# --- gripper marker (visual-servo end-effector tracking) --------------------
# An ArUco marker stuck flat on the gripper TOP face, centered on the approach
# (tip) axis, so its detected center maps (via the board homography) to the
# gripper-tip board position regardless of J6. Printed true-scale by
# marker_to_pdf.py. Detected full-frame; verified detectable when the room is
# lit and the gripper top face points up (i.e. in a top-down pose) — keep these
# detector params loose (small/blurry/oblique marker).
@dataclass(frozen=True)
class GripperMarkerSpec:
    # DICT_4X4_50 (same dict as the board) so ONE detector pass finds board +
    # gripper. id 49 is free (board uses 0-34). 4x4 has bigger cells than 5x5 =
    # far more robust to the specular glare/blur/curl that killed the first
    # DICT_5X5_100 marker. Print LARGE on MATTE paper, mount FLAT on a rigid card.
    dictionary: str = "DICT_4X4_50"
    marker_id: int = 49
    length_mm: float = 45.0


GRIPPER_MARKER = GripperMarkerSpec()


# --- grasp-height constraint -------------------------------------------------
# We do NOT recover object height from one camera. The pick Z is the board plane
# (known in base frame from touch calibration) plus a per-class grasp offset.
# Configure the object class you are picking here. `grasp_z_offset_mm` is how far
# ABOVE the board surface the gripper tip should close (e.g. half the object
# height for a centered top grasp, or the graspable-feature height).
@dataclass(frozen=True)
class GraspProfile:
    name: str = "default-large"
    grasp_z_offset_mm: float = 40.0          # tip closes this far above board plane
    approach_clearance_mm: float = 60.0      # pre-grasp hover above the grasp point
    retreat_mm: float = 80.0                 # lift after grasp


GRASP = GraspProfile()


# --- frame source ------------------------------------------------------------
# Two backends (see frame_source.py):
#   "rtsp"  : cv2.VideoCapture on a stream URL (best for calibration bursts; runs
#             on the Pi / robot host where the camera network is reachable).
#   "mcp"   : decode a base64 still saved from the soracam MCP get_live_still_image
#             tool result (one-shot glances; ~15 s/frame, not for bursts).
@dataclass(frozen=True)
class FrameSourceConfig:
    backend: str = field(default_factory=lambda: os.environ.get("SORACAM_BACKEND", "rtsp"))
    # For "rtsp": full URL. SORACAM unlimited live-view yields a short-lived URL;
    # put it here or in $SORACAM_STREAM_URL. (DASH URLs also work via ffmpeg.)
    stream_url: str = field(default_factory=lambda: os.environ.get("SORACAM_STREAM_URL", ""))
    device_id: str = field(default_factory=lambda: os.environ.get("SORACOM_DEVICE_ID", ""))


FRAME_SOURCE = FrameSourceConfig()


def artifact_path(name: str) -> str:
    return os.path.join(ARTIFACT_DIR, name)


def ensure_artifact_dir() -> str:
    os.makedirs(ARTIFACT_DIR, exist_ok=True)
    return ARTIFACT_DIR
